
import Footer from '@/components/footer/Footer'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/components/navbar/Navbar'
import  { Toaster } from 'react-hot-toast';



const inter = Inter({ subsets: ['latin'] })



export const metadata: Metadata = {
  title: 'Todo',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
   
    <html lang="en">
      <head>
        
      </head>
      <body className={inter.className}>
        <header>
          <Navbar/>
        </header>
        <main>
          {children}
        </main>
          <footer>
            <Footer/>
          </footer>
          <Toaster />
      </body>
    </html>
    
  )
}
